// The binlog package provides functionality for reading and parsing MySQL
// binary / relay log events.
//
// This package is a work in progress.  For now, it can handle a large
// subset of row based replication logs generated by MySQL 5.5 / 5.6 (It will
// probably work for query based replication logs as well).
//
// Additional documentation can be found here:
//  - Basic event structure: http://dev.mysql.com/doc/internals/en/event-structure.html
//  - Event type specific: payload structure http://dev.mysql.com/doc/internals/en/event-data-for-specific-event-types.html
//      NOTE: Some information are out-of-date / missing.  Refer to the source
//      code for absolute truth.
package binlog
