package binlog

import (
	mysql_proto "dropbox/proto/mysql"
)

// An artificial heartbeat event generated by the master. It isn't written to the relay logs.
//
// Common to 5.5, 5.6 and 5.7:
//      The Post-Header and Body of the event are empty.
//      The HeartbeatEvent only contains the Common-Header.
// 5.6 and 5.7 Specific:
//      (optional) 4 byte footer for checksum
// See https://dev.mysql.com/doc/internals/en/heartbeat-event.html for more details.
type HeartbeatEvent struct {
	Event
}

type heartbeatEventParser struct {
	V4EventParser
}

func newHeartbeatEventParser() V4EventParser {
	return &heartbeatEventParser{}
}

func (p *heartbeatEventParser) EventType() mysql_proto.LogEventType_Type {
	return mysql_proto.LogEventType_HEARTBEAT_LOG_EVENT
}

func (p *heartbeatEventParser) FixedLengthDataSize() int {
	return 0
}

// Heartbeat events have no table context to set.
func (p *heartbeatEventParser) SetTableContext(context TableContext) {
}

func (p *heartbeatEventParser) Parse(raw *RawV4Event) (Event, error) {
	event := &HeartbeatEvent{
		Event: raw,
	}
	return event, nil
}
